# Generated by Django 6.0.2 on 2026-02-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenileharvest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=255)),
                ('child_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.AddField(
            model_name='harvestpayment',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='juvenileharvest.family'),
        ),
    ]
