# Generated by Django 6.0.2 on 2026-03-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenileharvest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='category',
            field=models.CharField(choices=[('executive', 'Executive'), ('committee_with_family', 'Committee with Family'), ('single_committee', 'Single Committee'), ('family_one_child', 'Family with one child'), ('family_multiple_children', 'Family with multiple children'), ('grandparents', 'Grandparents')], default='family_one_child', max_length=32),
        ),
    ]
