# Generated by Django 6.0.2 on 2026-02-28 03:20

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenileharvest', '0002_family_harvestpayment_family'),
        ('pghistory', '0007_auto_20250421_0444'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestPaymentEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('check', 'Check'), ('credit_card', 'Credit Card')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='harvestpayment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "juvenileharvest_harvestpaymentevent" ("amount", "created_at", "description", "family_id", "id", "payment_date", "payment_method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at") VALUES (NEW."amount", NEW."created_at", NEW."description", NEW."family_id", NEW."id", NEW."payment_date", NEW."payment_method", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='08be87a5cd7cc58fcc90b1b2a91dc7ac9fcf5804', operation='INSERT', pgid='pgtrigger_insert_insert_5ecbc', table='juvenileharvest_harvestpayment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='harvestpayment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "juvenileharvest_harvestpaymentevent" ("amount", "created_at", "description", "family_id", "id", "payment_date", "payment_method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at") VALUES (NEW."amount", NEW."created_at", NEW."description", NEW."family_id", NEW."id", NEW."payment_date", NEW."payment_method", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='3c6b7ab7a20762878692534fcfdbc458354c9674', operation='UPDATE', pgid='pgtrigger_update_update_9b333', table='juvenileharvest_harvestpayment', when='AFTER')),
        ),
        migrations.AddField(
            model_name='harvestpaymentevent',
            name='family',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='juvenileharvest.family'),
        ),
        migrations.AddField(
            model_name='harvestpaymentevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='harvestpaymentevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='juvenileharvest.harvestpayment'),
        ),
    ]
