# Generated by Django 6.0.2 on 2026-03-02 23:30

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juvenileharvest', '0003_harvestpaymentevent_family_created_at_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='harvestpayment',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='harvestpayment',
            name='update_update',
        ),
        migrations.AddField(
            model_name='harvestpayment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='harvestpaymentevent',
            name='payer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='harvestpayment',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "juvenileharvest_harvestpaymentevent" ("amount", "created_at", "description", "family_id", "id", "payer_name", "payment_date", "payment_method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at") VALUES (NEW."amount", NEW."created_at", NEW."description", NEW."family_id", NEW."id", NEW."payer_name", NEW."payment_date", NEW."payment_method", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='20a063cb1502487740838064a3d75d656da67da4', operation='INSERT', pgid='pgtrigger_insert_insert_5ecbc', table='juvenileharvest_harvestpayment', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='harvestpayment',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "juvenileharvest_harvestpaymentevent" ("amount", "created_at", "description", "family_id", "id", "payer_name", "payment_date", "payment_method", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "updated_at") VALUES (NEW."amount", NEW."created_at", NEW."description", NEW."family_id", NEW."id", NEW."payer_name", NEW."payment_date", NEW."payment_method", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='783a142260fe561207809f6828c07954093c7cef', operation='UPDATE', pgid='pgtrigger_update_update_9b333', table='juvenileharvest_harvestpayment', when='AFTER')),
        ),
    ]
