# Generated by Django 6.0.2 on 2026-03-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juvenileharvest', '0004_remove_harvestpayment_insert_insert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestPaymentEventProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('juvenileharvest.harvestpaymentevent',),
        ),
    ]
